### ISSUE TITLE
Login button to have 'Coming soon' hover over

### ISSUE THREAD

**Issue by lickcreative** [oliverjam/workstream-website#23]
Needs to say 'Coming soon' on hover or click.

**Comment by oliverjam** [comment]
How's that?

**Comment by oliverjam** [comment]
Coming soon doesn't fit super well :/

**Comment by lickcreative** [comment]
Looks fine to me but I'm not keen on the cursor changing to having the little 'stop' sign on it. Would rather the pointer cursor. If this is not possible, all good, we can close this issue

**Comment by oliverjam** [comment]
Yeah I just did it for fun to make it obvious it's disabled.

When you say pointer you mean the link cursor? The hand with the finger?

**Comment by Jamchiller** [comment]
Yep link cursor. Hand with finger. I tried to look up the official name and was on the fence between 'link selector cursor' and 'pointer'

**Comment by oliverjam** [comment]
I'm not sure that using a link cursor for a button that doesn't go anywhere is a good idea. 

https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by Jamchiller** [comment]
Eh I don’t think that’s a consensus opinion. As the guy in the comments says, google uses the pointer for buttons. So do apple, quite often. Medium do, and even the comment button under this box does. So definitely just whether you think you want to provide an affordance

**Comment by Jamchiller** [comment]
Definitely an interesting article though. One thing I would say is that his clickbaity 'no button should have a hand cursor' comment isn't very nuanced - there are other reasons why you would use it. Using the google search page as an example, which I'm sure has had millions spent on it in UX testing, they've included a hand cursor over the 'tools' button. It has everything the dude has pointed out - it's a button, it has visual feedback and strong affordances, and yet they've applied a hand cursor. I'd say this is mainly for consistency's sake. You have 'all', 'images', etc, that are all links, and hence need a hand cursor. And so it would be weird to have a button next to it that doesn't trigger the hand cursor, because this could cause confusion on whether the button is actually clickable or not. In the same way, I think that since our 'about' and 'contact' have a hand pointer, the button should too

**Comment by Jamchiller** [comment]
But it's not that important. Kinda just interested by the question. Was not aware that people were pushing for the removal of hand pointers from buttons

**Comment by oliverjam** [comment]
It's pushing for leaving buttons in their default state. There's a reason links have a special cursor and buttons don't in every browser. Links are a special web thing and have a special cursor to indicate that. Buttons in native apps for example don't use different cursors. Pointers aren't for indicating clickability, they're to indicate that clicking it will take you to another location.

Having thought about it though in this case 'Log In' is just a link that looks like a button. It's going to take you to a totally different webpage right? So it probably makes sense to use a pointer.

I think the takeaway from the article is that you shouldn't just have all your buttons have pointers by default — you need to think about the use-case.

**Comment by Jamchiller** [comment]
I think you're being a little nice on the writer of the article. Although I agree with him on the whole, he doesn't say 'think about the use-case', he says 'The hand cursor is reserved for links.' Which is the opposite of thinking about the use-case. And none of this addresses the fact that Google break this rule on their most important page. 

 But cool, yeah you're right, it is a link so defo a hand pointer.

**Comment by oliverjam** [comment]
Why are Google relevant? They could be wrong just as much as anyone else. I think the definition of wrong here is important.

From my perspective as someone who values the web and the way things are supposed to work this is 'wrong', but it might be 'right' for certain groups of users.

**Comment by Jamchiller** [comment]
Google are relevant for a number of reasons: 
- User expectations: When we're talking about what a user expects and doesn't expect, a good way of understanding this is looking at how the sites they visit the most operate. If there hasn't been a massive problem for google including a hand pointer button, then maybe it's not an issue for users.
- Web standards. Google are an internet leader, they create web standards. If it's alright for them, then there's definitely a lot more nuance than what is portrayed in the article. 
- Investment: There's only a few ways we can understand what is making the UX easier or harder, and one of those is user testing and research. Looking at a site like Google is helpful because they have most certainly considered this question, invested in it, and made a decision on it. And because of this I disagree that they could be as wrong as anyone else. If you're defining wrong as 'what is best for the user', then they are much less likely to be wrong than some dude who threw together a website for himself without considering or testing why elements on the page act in the way that they do. 

And yes you're right, wrong and right vary based on who you ask, and this is all the more reason why a nuanced approach is better, rather than a 'this is how this should work in all cases' approach.

**Comment by oliverjam** [comment]
Yeah I guess google.com is probably the most user-tested site in the world.

Staying on topic: I'll push a change to use a pointer instead of the disabled cursor.

**Comment by Jamchiller** [comment]
Haha okay :) Nice!
