### ISSUE TITLE
Add test iPhone video

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/workstream-website#24]

**Comment by lickcreative** [comment]
This is everything

**Comment by Jamchiller** [comment]
Okay I've added the real video into the folder now. If you need it smaller then I can try downsize it for you

**Comment by Jamchiller** [comment]
Additionally, are you okay making the attached image in CSS? Or do you want me to send you the iMac image? Happy for you to use a laptop instead of the imac.  
![screen shot 2017-03-22 at 17 53 33](https://cloud.githubusercontent.com/assets/16238581/24212817/7ab888ec-0f28-11e7-8e07-f16a93ed79cf.png)

**Comment by oliverjam** [comment]
Did we not decide to just have a single iPhone with a video in it?
